const today = (hour, days = 0) => { const d = new Date(); d.setDate(d.getDate() - days); d.setHours(hour, 15, 0, 0); return d.toISOString(); };
export function seedData() {
  const people = ['Marina Costa', 'Rafael Lima', 'João Pedro', 'Ana Souza', 'Carlos Nunes', 'Beatriz Santos', 'Lucas Oliveira', 'Fernanda Alves', 'Pedro Silva', 'Camila Rocha', 'Gabriel Pereira', 'Juliana Martins'];
  const users = people.map((fullName, i) => ({ id: `u${i+1}`, uid: `u${i+1}`, fullName, email: `pessoa${i+1}@exemplo.com`, phone: '(91) 90000-0000', city: 'Curuçá, PA', profileComplete: true, driverApproved: i < 5 }));
  const drivers = people.slice(0, 5).map((name, i) => ({ id: `u${i+1}`, uid: `u${i+1}`, name, vehicleModel: ['Chevrolet Spin', 'Honda CG 160', 'Fiat Doblò', 'Toyota Etios', 'Yamaha Fazer 250'][i], vehicleColor: ['Prata', 'Preta', 'Branca', 'Vermelho', 'Azul'][i], vehicleType: [1,4].includes(i) ? 'motorcycle' : 'car', serviceType: [0,2].includes(i) ? 'shared' : 'private', origin: ['Centro', 'Terminal', 'Barcarena', 'Centro', 'Pioneiro'][i], destination: ['Vila dos Cabanos', 'Praia do Caripi', 'Vila dos Cabanos', 'Terminal Rodoviário', 'Centro'][i], priceCents: [1200,900,1500,2400,1100][i], seatsTotal: [6,1,7,4,1][i], seatsAvailable: [3,1,5,4,1][i], online: i !== 4 }));
  const trips = Array.from({ length: 32 }, (_, i) => ({ id: `TC${String(1048-i)}`, passengerId: `u${6+i%7}`, driverId: `u${1+i%5}`, routeId: `rota-${i%5}`, seats: i%3 === 0 ? 2 : 1, status: i < 2 ? 'in_progress' : i < 5 ? 'confirmed' : i === 6 ? 'cancelled' : 'completed', createdAt: today(8+i%10, Math.floor(i/5)) }));
  const driverApplications = [8,9,10].map((n,i) => ({ id: `u${n}`, userId: `u${n}`, vehicleModel: ['Renault Kwid', 'Honda Pop 110i', 'Chevrolet Onix'][i], vehicleType: i === 1 ? 'motorcycle' : 'car', plate: ['ABC1D23', 'DEF4G56', 'GHI7J89'][i], status: 'pending', submittedAt: today(8, i) }));
  const chats = [{ id: 'chat-1', participantIds: ['u1', 'u6'], tripId: 'TC1048', lastMessage: 'Combinado! Estou em frente ao mercado.', updatedAt: today(10), messages: [{ id:'m1', senderId:'u6', text:'Olá! Estou perto do mercado municipal.', sentAt:today(9) }, { id:'m2', senderId:'u1', text:'Ótimo, chego ao ponto em 5 minutos.', sentAt:today(9) }, { id:'m3', senderId:'u6', text:'Combinado! Estou em frente ao mercado.', sentAt:today(10) }] }];
  const admins = [{ id: 'demo-admin', name: 'Administrador', email: 'admin@exemplo.com', active: true, createdBy: 'demo-admin', createdAt: today(8), updatedAt: today(8) }];
  return { users, drivers, trips, driverApplications, chats, admins };
}
export const money = cents => (Number(cents || 0)/100).toLocaleString('pt-BR', { style:'currency', currency:'BRL' });
export const dateValue = v => v == null ? null : typeof v.toDate === 'function' ? v.toDate() : new Date(v._seconds != null ? v._seconds*1000 : v.seconds != null ? v.seconds*1000 : v);
export const dateLabel = v => { const d = dateValue(v); return d && !isNaN(d) ? d.toLocaleString('pt-BR', { day:'2-digit', month:'short', hour:'2-digit', minute:'2-digit' }) : 'Não informado'; };
export const statusLabels = { pending:'Em análise', approved:'Aprovado', rejected:'Recusado', requested:'Nova solicitação', confirmed:'Confirmada', accepted:'Aceita', in_progress:'Em andamento', completed:'Concluída', cancelled:'Cancelada' };
export const nextStatuses = { requested:['accepted','cancelled'], confirmed:['accepted','cancelled'], accepted:['in_progress','cancelled'], in_progress:['completed'], completed:[], cancelled:[] };
export function loadDemo() { try { const saved = JSON.parse(localStorage.getItem('taxi-curuca-demo-v1')); if (saved && ['users','drivers','trips','driverApplications','chats'].every(k => Array.isArray(saved[k]))) return saved; } catch { /* Start a fresh demo if the local data is invalid. */ } return seedData(); }
export function persistDemo(data) { localStorage.setItem('taxi-curuca-demo-v1', JSON.stringify(data)); }
